#include "stm32h7xx.h"
#include "stm32h743xx.h"
extern uint32_t SystemCoreClock; 

void SystemClock_Configgg(void)
{

    PWR->CR3 |= PWR_CR3_LDOEN;
    PWR->D3CR = (PWR->D3CR & ~PWR_D3CR_VOS) | (PWR_D3CR_VOS_0 | PWR_D3CR_VOS_1);
    while ((PWR->D3CR & PWR_D3CR_VOSRDY) == 0) {}
    
    FLASH->ACR = (FLASH->ACR & ~(FLASH_ACR_LATENCY | FLASH_ACR_WRHIGHFREQ)) |
                (FLASH_ACR_LATENCY_4WS | (FLASH_ACR_WRHIGHFREQ_1));
    while((FLASH->ACR & FLASH_ACR_LATENCY) != FLASH_ACR_LATENCY_4WS){}

    RCC->CR |= RCC_CR_HSION;
    while ((RCC->CR & RCC_CR_HSIRDY) == 0) {}

    RCC->CR &= ~RCC_CR_PLL1ON;
    while((RCC->CR & RCC_CR_PLL1RDY) != 0) {}


    RCC->PLLCKSELR = (RCC->PLLCKSELR & ~RCC_PLLCKSELR_PLLSRC) | RCC_PLLCKSELR_PLLSRC_HSI;
    RCC->PLLCKSELR = (RCC->PLLCKSELR & ~RCC_PLLCKSELR_DIVM1) | ((4U - 1U)  << RCC_PLLCKSELR_DIVM1_Pos);
    RCC->PLL1DIVR = ((30U - 1U) << RCC_PLL1DIVR_N1_Pos) |
                    ((1U - 1U)  << RCC_PLL1DIVR_P1_Pos) |
                    ((2U - 1U)  << RCC_PLL1DIVR_Q1_Pos) | 
                    ((2U - 1U)  << RCC_PLL1DIVR_R1_Pos); 

    // RCC->PLLCFGR |= RCC_PLLCFGR_PLL1VCOSEL | RCC_PLLCFGR_PLL1RGE_2;
    RCC->PLLCFGR = (RCC->PLLCFGR & ~(RCC_PLLCFGR_PLL1RGE | RCC_PLLCFGR_PLL1VCOSEL)) | RCC_PLLCFGR_PLL1VCOSEL | RCC_PLLCFGR_PLL1RGE_3;

    RCC->PLLCFGR |= RCC_PLLCFGR_DIVP1EN | RCC_PLLCFGR_DIVQ1EN | RCC_PLLCFGR_DIVR1EN;
    RCC->PLLCFGR &= ~RCC_PLLCFGR_PLL1FRACEN;
    RCC->CR |= RCC_CR_PLL1ON;
    while ((RCC->CR & RCC_CR_PLL1RDY) == 0) {}

    // RCC->D1CFGR = (0U << RCC_D1CFGR_D1CPRE_Pos) | (0x8U << RCC_D1CFGR_HPRE_Pos) | (0x4U << RCC_D1CFGR_D1PPRE_Pos);
    RCC->D1CFGR = RCC_D1CFGR_D1CPRE_DIV1 | RCC_D1CFGR_HPRE_DIV2 | RCC_D1CFGR_D1PPRE_DIV2;
    // RCC->D2CFGR = (0x4U << RCC_D2CFGR_D2PPRE1_Pos) | (0x4U << RCC_D2CFGR_D2PPRE2_Pos);
    RCC->D2CFGR = RCC_D2CFGR_D2PPRE1_DIV2 | RCC_D2CFGR_D2PPRE2_DIV2;
    // RCC->D3CFGR = (0x4U << RCC_D3CFGR_D3PPRE_Pos);
    RCC->D3CFGR = RCC_D3CFGR_D3PPRE_DIV2;

    RCC->CFGR = (RCC->CFGR & ~RCC_CFGR_SW) | RCC_CFGR_SW_PLL1;
    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL1) {}

    SystemCoreClock = 480000000;
}
